stages:
  - linting
  - build
  - test

services:
  - docker:dind  

image: docker:latest 

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""    # Disabled TLS for DinD
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1
  COMPOSE_PROFILES: neo4jTest
  OPENAI_API_KEY: ""
  ORGANIZATION_KEY: ""
  PROJECT_KEY: ""
  DOCKER_CONFIG: ${DOCKER_CONFIG:-$HOME/.docker}

black:
  stage: linting
  tags:
    - digiheals
  image: registry.gitlab.com/pipeline-components/black:latest
  script:
    - black --check .

# flake8:
#   stage: linting
#   tags:
#     - digiheals
#   image: python:3.10-slim
#   script:
#     - pip install --no-cache-dir --upgrade pip
#     - pip install --no-cache-dir flake8
#     - flake8 .


build_image_job:
  stage: build
  tags:
    - digiheals

  before_script:
    - echo "Setting up Docker BuildKit..."
    - mkdir -p $DOCKER_CONFIG/cli-plugins

  script:
    # Log into registry
    - echo "$CI_REGISTRY_PASSWORD" | docker login registry-tigr.narfs.co -u "$CI_REGISTRY_USER" --password-stdin

    # Tag and build Docker image
    - export IMAGE_TAG=registry-tigr.narfs.co/digiheals/docker:${CI_COMMIT_REF_SLUG}
    - docker build -t $IMAGE_TAG .
    
    # Push image to registry
    - docker push $IMAGE_TAG

    # Tag as 'latest' if on staging branch
    - |
      if [ "$CI_COMMIT_REF_NAME" == "staging" ]; then
        docker tag $IMAGE_TAG registry-tigr.narfs.co/digiheals/docker:latest
        docker push registry-tigr.narfs.co/digiheals/docker:latest
      fi


build_job:
  stage: build

  tags:
    - digiheals

  script:
    - docker pull registry-tigr.narfs.co/digiheals/docker:${CI_COMMIT_REF_SLUG} || docker pull registry-tigr.narfs.co/digiheals/docker:latest
    
    - docker compose up -d

    - sleep 480  # Wait for services to initialize

test_job:
  stage: test

  tags:
    - digiheals

  script:
    # Run tests
    - make test

  after_script:
    # Tear down containers
    - docker compose down -v
