repos:
-   repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
    - id: black
      language_version: python3.11.2
-   repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    args: ['--ignore=E501']
    hooks:
    -   id: flake8
