name: ehrgarden

services:
  db-gnuhealth:
    image: postgres:alpine3.20
    restart: always
    environment:
      POSTGRES_USER: gnuhealth
      POSTGRES_DB: health
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 127.0.0.1:5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s 

  gnuhealth:
    depends_on:
      - db-gnuhealth
    build: ./ehr-garden/gnuhealth
    image: gnuhealth:4.4.0
    restart: always
    ports:
      - 127.0.0.1:8000:8000

  db-openemr:
    image: mariadb:11.4.2
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
    ports:
      - 127.0.0.1:3306:3306
    volumes:
    - db-openemr-vol:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 30s
      interval: 30s
      timeout: 5s
      retries: 3

  openemr:
    depends_on:
      - db-openemr
    build: ./ehr-garden/openemr
    image: openemr:7.0.2
    restart: always
    environment:
      MYSQL_HOST: db-openemr
      MYSQL_ROOT_PASS: root
      MYSQL_USER: openemr
      MYSQL_PASS: openemr
      OE_USER: admin
      OE_PASS: pass
    ports:
      - 127.0.0.1:8001:8001
      - 127.0.0.1:8443:443
    volumes:
    - openemr-sitevolume:/var/www/localhost/htdocs/openemr/sites
    - openemr-logvolume01:/var/log

  vista:
    image: worldvista/vehu:201911-syn-fhir
    container_name: vehu
    ports:
      - 127.0.0.1:9080:9080
      
  fhir-vista:
    image: worldvista/fhir-on-vista:latest
    ulimits:
      nofile:
        soft: 8096
        hard: 8096
    ports:
      - 127.0.0.1:8002:8080
    depends_on:
      - vista

  openmrs-db:
    image: mariadb:10.3
    command: "mysqld --character-set-server=utf8 --collation-server=utf8_general_ci"
    environment:
      MYSQL_DATABASE: ${OMRS_DB_NAME:-openmrs}
      MYSQL_USER: ${OMRS_DB_USER:-openmrs}
      MYSQL_PASSWORD: ${OMRS_DB_PASSWORD:-openmrs}
      MYSQL_ROOT_PASSWORD: ${OMRS_DB_ROOT_PASSWORD:-openmrs}
    healthcheck:
      test: "mysql --user=${OMRS_DB_USER:-openmrs} --password=${OMRS_DB_PASSWORD:-openmrs} --execute \"SHOW DATABASES;\""
      interval: 3s
      timeout: 5s
      retries: 3
    volumes:
      - db-data:/var/lib/mysql

  openmrs:
    image: openmrs/openmrs-core:${TAG:-nightly}
    build: ./ehr-garden/openmrs
    ports:
      - 127.0.0.1:8003:8080
    environment:
      OMRS_DB_HOSTNAME: ${OMRS_DB_HOSTNAME:-openmrs-db}
      OMRS_DB_NAME: ${OMRS_DB_NAME:-openmrs}
      OMRS_DB_USERNAME: ${OMRS_DB_USERNAME:-openmrs}
      OMRS_DB_PASSWORD: ${OMRS_DB_PASSWORD:-openmrs}
      OMRS_ADMIN_USER_PASSWORD: ${OMRS_ADMIN_USER_PASSWORD:-Admin123}
      OMRS_ADMIN_PASSWORD_LOCKED: ${OMRS_ADMIN_PASSWORD_LOCKED:-true}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/openmrs"]
      interval: 3s
      timeout: 5s
      retries: 3
    volumes:
      - openmrs-data:/openmrs/data/

  hapi-fhir:
    image: hapiproject/hapi:latest
    ports:
      - 127.0.0.1:8004:8080

  ibm-fhir:
    image: ghcr.io/linuxforhealth/fhir-server
    ports:
      - 127.0.0.1:8005:9443
    environment:
      BOOTSTRAP_DB: true

  blaze:
    image: samply/blaze:latest
    ports:
      - 127.0.0.1:8006:8080

  # Images after this are not FHIR images
  synthea:
    image: synthea
    build: ./ehr-garden/synthea
    ports:
      - 127.0.0.1:9000:9000
    volumes:
      - ./files:/synthea/output

  neo4j:
    image: neo4j:5.19.0-bullseye
    environment:
      NEO4J_AUTH: neo4j/fhir-garden
    ports:
      - 127.0.0.1:7474:7474
      - 127.0.0.1:7687:7687
    volumes:
      - neo4jvolume:/data
  java-json-echo:
    build: ./json-garden/java
    restart: always
    ports:
      - 127.0.0.1:8181:8080
    networks:
      - public
  clojure-json-echo:
    build: ./json-garden/clojure
    restart: always
    ports:
      - 127.0.0.1:8282:3000
    networks:
      - public

networks:
  # The presence of these objects is sufficient to define them
  public: {}
  private: {}

volumes:
  openemr-logvolume01: {}
  openemr-sitevolume: {}
  db-openemr-vol: {}
  db-data:
  openmrs-data:
  blaze-data:
  neo4jvolume:
