name: ehrgarden

services:

  vista:
    image: ${CI_REGISTRY_IMAGE}/vista-vehu:${CI_COMMIT_REF_SLUG}
    ports:
      - 127.0.0.1:9080:9080
      
  fhir-vista:
    depends_on:
      - vista
    image: ${CI_REGISTRY_IMAGE}/vista-fhir:${CI_COMMIT_REF_SLUG}
    ulimits:
      nofile:
        soft: 8096
        hard: 8096
    ports:
      - 127.0.0.1:8002:8080

  hapi-fhir:
    image: ${CI_REGISTRY_IMAGE}/hapi-fhir:${CI_COMMIT_REF_SLUG}
    ports:
      - 127.0.0.1:8004:8080

  ibm-fhir:
    image: ${CI_REGISTRY_IMAGE}/ibm-fhir:${CI_COMMIT_REF_SLUG}
    environment:
      BOOTSTRAP_DB: true
    ports:
      - 127.0.0.1:8005:9443

  blaze:
    image: ${CI_REGISTRY_IMAGE}/blaze-fhir:${CI_COMMIT_REF_SLUG}
    ports:
      - 127.0.0.1:8006:8080

  intersystems:
    image: ${CI_REGISTRY_IMAGE}/iris-fhir:${CI_COMMIT_REF_SLUG}  
    hostname: fhir-template

    ports: 
      - 32782:1972
      - 8007:52773
      - 32784:53773
    command: 
      - -a
      - iris session iris -U%SYS '##class(Security.Users).UnExpireUserPasswords("*")'
      - --check-caps false
    volumes:
      - ./data:/data
      - ./:/home/irisowner/irisdev

  synthea:
    image: ${CI_REGISTRY_IMAGE}/synthea:${CI_COMMIT_REF_SLUG}
    ports:
      - 127.0.0.1:9000:9000
    volumes:
      - ./files:/synthea/output
  
  neo4j-test:
    image: ${CI_REGISTRY_IMAGE}/neo4j-test:${CI_COMMIT_REF_SLUG}
    container_name: neo4jTest
    environment:
      NEO4J_AUTH: neo4j/test-garden
    ports:
      - 127.0.0.1:7475:7474
      - 127.0.0.1:7688:7687
    profiles: 
      - neo4jTest


volumes:
  blaze-data:
  neo4jTestvolume: {}

