# Use postgres/example user/password credentials
version: '3.1'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: gnuhealth
      POSTGRES_DB: health
      POSTGRES_HOST_AUTH_METHOD: trust
    networks:
      - private
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - public
      - private
    depends_on:
      - db

  gnuhealth:
    build: ./gnuhealth
    restart: always
    ports:
      - 8000:8000
    networks:
      - public
      - private
    depends_on:
      - db
  mysql:
    restart: always
    image: mariadb:10.11
    command: ['mysqld','--character-set-server=utf8mb4']
    volumes:
    - databasevolume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
  openemr:
    restart: always
    image: openemr #/openemr:6.0.0
    build: ./openemr
    ports:
    - 8001:8001
    - 443:443
    volumes:
    - sitevolume:/var/www/localhost/htdocs/openemr/sites
    - logvolume01:/var/log
    environment:
      MYSQL_HOST: mysql
      MYSQL_ROOT_PASS: root
      MYSQL_USER: openemr
      MYSQL_PASS: openemr
      OE_USER: admin
      OE_PASS: pass
    depends_on:
    - mysql

networks:
  # The presence of these objects is sufficient to define them
  public: {}
  private: {}

volumes:
  logvolume01: {}
  sitevolume: {}
  databasevolume: {}
